# 此配置文件下的所有数据只可增加，不可删除。

[fields]
姓名 = name
拍片 = pp
牙粉 = yf
漱口水 = sks
牙套清洁液 = qjy
洁牙机头 = jyj
指尖采血 = cx
美团89 = m1
美团69 = m2
美团喷砂149 = m3
抖音89 = d1
抖音69 = d2
抖音喷砂149 = d3
未收费洁牙 = free

# fields中的内容应与amounts同步增加
[amounts]
pp = 20
yf = 5
sks = 2
qjy = 2
jyj = 3
cx = 5
m1 = 30
m2 = 10
m3 = 40
d1 = 30
d2 = 10
d3 = 40
free = 20


